// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternal(arg1) {
  return window['go']['app']['App']['OpenExternal'](arg1);
}

export function OpenInterface() {
  return window['go']['app']['App']['OpenInterface']();
}

export function Platform() {
  return window['go']['app']['App']['Platform']();
}

export function Restart() {
  return window['go']['app']['App']['Restart']();
}

export function Start() {
  return window['go']['app']['App']['Start']();
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}
