// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {harness} from '../models';

export function OpenInterface():Promise<void>;

export function Platform():Promise<string>;

export function Restart():Promise<harness.Status>;

export function Start():Promise<harness.Status>;

export function Status():Promise<harness.Status>;

export function Stop():Promise<void>;
